### ISSUE TITLE
precision-recall plot 

### ISSUE THREAD

**Issue by chienchi** [Cibiv/Teaser#1]
Hi Teaser developers,

Thanks for the great tool for the reads mapper benchmark. It provides a nice context for evaluating the performance of read mappers. I am wondering, would it be possible to change the precision-recall plot to a 2D plot (i.e. precision vs recall) instead of the current grouped bar chart?   Since the difference is < 1% most of time, the bar chart is hard to distinguish among the mapper. 

Thanks,
Chienchi

**Comment by smolkmo** [comment]
Hello there,

Thank you for your interest in Teaser and your helpful suggestion. We now changed the precision/recall plot to a scatter plot since it indeed aids readability, as you pointed out.

Cheers,
Moritz

**Comment by chienchi** [comment]
Thanks very much for the quick response.
