### ISSUE TITLE
Web page not found

### ISSUE THREAD

**Issue by denise0593** [Cibiv/Teaser#15]
Hi! I was looking at your software, I was trying to open the webpage example but it returns an error 
"Service Temporarily Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Temporarily Unavailable error was encountered while trying to use an ErrorDocument to handle the request."
Thanks

**Comment by smolkmo** [comment]
Hi Denise,

thanks for your report. The Teaser web app is now up again at http://teaser.cibiv.univie.ac.at/

Moritz
